name: Auto Push

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit and push changes
        run: |
          git config --local user.email "tanmaysomani2003@gmail.com"
          git config --local user.name "Tanmay-Somani"

          cd "My Website" 
          git add .
          git commit -m "Auto push changes"
          git push
