name: Auto Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "auto: update files"
          git push

